version: '3'

services:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mydata:/data/db
    networks:
      - mynetwork
    ports:
      - '27017:27017'
    logging:
      driver: 'none'

volumes:
  mydata:

networks:
  mynetwork:
